- hosts: docker
  become: yes
  tasks:
    - name: Deploy Apps
      docker_container:
        name: collar-admin
        image: 20.100.1.191:5000/smf/collar-admin:<tag_placeholder>
        state: started
        recreate: yes
        ports:
          - "4000:4000"